import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { projectTools } from '../src/project/tools'
import { createContextStore } from '../src/rdf/document-loader'
import { createFindings } from '../src/rdf/findings'
import { quadsFromJsonLd } from '../src/rdf/ingest'
import { createSessionGraph } from '../src/rdf/session-graph'
import { GRAPHS } from '../src/rdf/terms'
import { buildCapabilityModel, constraintsFor, constraintsOfShape } from '../src/vocab/capability'

import shapes from '../test/fixtures/mago-shapes.json'
import vocab from '../test/fixtures/mago-vocab.json'

/**
 * The conformance report (task 8.6).
 *
 * Everywhere the client cannot act because the API describes something incompletely, it records the
 * omission instead of working around it. Those findings are about the **API**, not about this client,
 * so they are input to later server-side changes and to nothing here.
 *
 * This runs the real pipeline — ingest, capability model, projection — over the vocabulary and shapes
 * graph captured verbatim from a live boot, and writes what the client itself recorded. It is not a
 * transcription of anyone's notes: every statement in the output was produced by the code that would
 * have produced it during a connect.
 *
 *     wsl zsh -lic 'cd "…/src/Web/HydraClient" && npm run report'
 *
 * **Scope, stated in the report itself rather than left to be discovered.** Four of the nine finding
 * kinds are detectable from published documents alone and are what this exports. The other five need
 * a live connect — an unreachable or invalid `@context`, an origin mismatch, an undeclared pagination
 * route, abbreviated members — because each is a fact about a *response*, not about a description.
 * Those were observed during stages 3 and 5 and are written up as C1–C5 in the change's `baseline.md`.
 * A report that quietly omitted them would read as an API with fewer gaps than it has.
 */

const VOCAB_URL = 'http://localhost:1648/Api/Vocab'
const SHAPES_URL = 'http://localhost:1648/Api/Shapes'

// A stable home beside the client. The report used to write into the consuming openspec change's
// directory, and broke the same way twice: archiving the change removes the directory. A change
// that wants a snapshot of record copies this file into its own directory instead.
const output = fileURLToPath(new URL('../conformance-report.ttl', import.meta.url))

const HEADER = `# Conformance findings — Hydra reference client
#
# Generated by tools/conformance-report.ts in src/Web/HydraClient. Do not hand-edit: regenerate with
#   npm run report
#
# Each finding is something the API does not declare, which cost the client an affordance it would
# otherwise have had. They are input to later SERVER-SIDE changes. Nothing here is a defect in the
# client, and nothing here is a request to change it.
#
# SCOPE. These are the findings detectable from the published vocabulary and shapes graph alone,
# read as RDF. Five further kinds — unreachable @context, invalid @context, origin mismatch,
# undeclared pagination route, abbreviated collection members — are facts about a RESPONSE rather
# than about a description, so they need a live connect and are not in this file. They were observed
# during stages 3 and 5 and are written up as C1-C5 in baseline.md, alongside this report.
#
# Source documents: the vocabulary and shapes graph captured verbatim from a live boot
# (test/fixtures/mago-vocab.json, test/fixtures/mago-shapes.json).

`

async function main(): Promise<void> {
  const graph = createSessionGraph()
  // The network must not be reached: the report has to be a function of the captured documents, or
  // regenerating it on a different day would produce a different answer for reasons nothing records.
  const load = createContextStore({
    fetchJson: async (url) => {
      throw new Error(`the network must not be reached, but ${url} was requested`)
    },
  }).load

  graph.ingestDocument(await quadsFromJsonLd(vocab, load, VOCAB_URL), GRAPHS.vocab)
  graph.ingestDocument(await quadsFromJsonLd(shapes, load, SHAPES_URL), GRAPHS.shapes)

  const findings = createFindings()
  projectTools(buildCapabilityModel(graph), {
    constraintsFor: (classIri) => constraintsFor(graph, classIri),
    constraintsOfShape: (shapeIri) => constraintsOfShape(graph, shapeIri),
    findings,
  })

  const turtle = await findings.toTurtle()
  writeFileSync(output, HEADER + turtle, 'utf8')

  const byKind = new Map<string, number>()
  for (const finding of findings.all()) {
    byKind.set(finding.kind, (byKind.get(finding.kind) ?? 0) + 1)
  }

  process.stdout.write(`${findings.all().length} findings written to ${output}\n`)
  for (const [kind, count] of [...byKind].sort()) {
    process.stdout.write(`  ${count.toString().padStart(4)}  ${kind}\n`)
  }
}

await main()
